// sw.js — service worker: the whole app cached for offline use.
//
// Cache-first for the app shell (it is fully static). bump.py increments CACHE
// and regenerates ASSETS from the files on disk; a new CACHE is what makes the
// installed app notice a release and offer "Update".

const CACHE = 'shoeschool-v1';

const ASSETS = [
  // <assets> — generated by bump.py, do not edit by hand
  './',
  './index.html',
  './manifest.webmanifest',
  // </assets>
];

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE)
      // cache:'reload' so a version bump always pulls fresh files, never a stale HTTP-cache copy
      .then((cache) => cache.addAll(ASSETS.map((u) => new Request(u, { cache: 'reload' })))),
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('message', (event) => {
  if (event.data === 'skipWaiting') self.skipWaiting();
});

self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET' || new URL(req.url).origin !== self.location.origin) return;
  event.respondWith(
    caches.match(req, { ignoreSearch: true }).then((hit) => hit || fetch(req).then((res) => {
      if (res.ok) { const copy = res.clone(); caches.open(CACHE).then((c) => c.put(req, copy)); }
      return res;
    }).catch(() => caches.match('./index.html'))),
  );
});
