// sw.js — service worker: the whole app cached for offline use.
//
// Cache-first for the app shell (it is fully static). bump.py increments CACHE
// and regenerates ASSETS from the files on disk; a new CACHE is what makes the
// installed app notice a release and offer "Update".

const CACHE = 'shoeschool-v2';

const ASSETS = [
  // <assets> — generated by bump.py, do not edit by hand
  './',
  './index.html',
  './manifest.webmanifest',
  './css/style.css',
  './js/app.js',
  './js/data/charts.js',
  './js/data/deviations.js',
  './js/data/glossary.js',
  './js/data/lessons.js',
  './js/data/sources.js',
  './js/data/tcedges.js',
  './js/drills/bet-ramp.js',
  './js/drills/bs-flash.js',
  './js/drills/bs-hands.js',
  './js/drills/common.js',
  './js/drills/count-pairs.js',
  './js/drills/count-tags.js',
  './js/drills/dealer-rules.js',
  './js/drills/deck-countdown.js',
  './js/drills/deck-estimation.js',
  './js/drills/deviation-flash.js',
  './js/drills/hand-total.js',
  './js/drills/index.js',
  './js/drills/payouts.js',
  './js/drills/rule-spot.js',
  './js/drills/running-count.js',
  './js/drills/true-count.js',
  './js/engine/de.js',
  './js/engine/dealer.js',
  './js/engine/ev.js',
  './js/engine/hilo.js',
  './js/engine/indices.js',
  './js/engine/risk.js',
  './js/engine/rng.js',
  './js/engine/rules.js',
  './js/engine/shoe.js',
  './js/engine/sim.js',
  './js/engine/simworker.js',
  './js/engine/strategy.js',
  './js/engine/worker.js',
  './js/game/barchart.js',
  './js/game/cards.js',
  './js/game/chartview.js',
  './js/game/content.js',
  './js/game/dechart.js',
  './js/game/linechart.js',
  './js/game/rampmath.js',
  './js/game/ramps.js',
  './js/game/sessionvalue.js',
  './js/game/shared.js',
  './js/game/table.js',
  './js/game/tray.js',
  './js/store.js',
  './js/ui.js',
  './js/views/about.js',
  './js/views/charts.js',
  './js/views/drill.js',
  './js/views/glossary.js',
  './js/views/learn.js',
  './js/views/lesson.js',
  './js/views/more.js',
  './js/views/play.js',
  './js/views/settings.js',
  './js/views/tools.js',
  './js/views/train.js',
  './icons/icon-192.png',
  './icons/icon-512.png',
  './icons/icon-maskable-512.png',
  './icons/icon.svg',
  // </assets>
];

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE)
      // cache:'reload' so a version bump always pulls fresh files, never a stale HTTP-cache copy
      .then((cache) => cache.addAll(ASSETS.map((u) => new Request(u, { cache: 'reload' })))),
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('message', (event) => {
  if (event.data === 'skipWaiting') self.skipWaiting();
});

self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET' || new URL(req.url).origin !== self.location.origin) return;
  event.respondWith(
    caches.match(req, { ignoreSearch: true }).then((hit) => hit || fetch(req).then((res) => {
      if (res.ok) { const copy = res.clone(); caches.open(CACHE).then((c) => c.put(req, copy)); }
      return res;
    }).catch(() => caches.match('./index.html'))),
  );
});
