// Precomputes the player's edge at each Hi-Lo true count for every classic
// preset -> js/data/tcedges.js. The session summary uses it to say what a
// student's bets were worth ("bet x edge at the count you bet at").
//
// Method: for true count t, the engine's representative Hi-Lo shoe
// (shoe.js shoeAtTrueCount: the cards a running count of t*D implies, removed
// evenly within each Hi-Lo group) at D = the decks typically left mid-shoe,
// priced with composition-dependent perfect play (ev.js houseEdgeCD), with the
// preset's own blackjack payout. Double Exposure is not covered (the summary
// falls back to the 0.5%-per-count rule there).
//
// Run: node scripts/build-tcedges.mjs   (about a minute)
import { writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { PRESETS, rulesFor } from '../js/engine/rules.js';
import { shoeAtTrueCount } from '../js/engine/shoe.js';
import { makeGame, houseEdgeCD } from '../js/engine/ev.js';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const TC_MIN = -8, TC_MAX = 10;
const out = {};
const t0 = Date.now();

for (const p of PRESETS) {
  const rules = rulesFor(p.id);
  if (rules.variant !== 'classic') continue;
  // decks typically left when a bet is made: halfway through the dealt part. At
  // least one deck: the linear model shoe has fractional card counts, and below a
  // deck a few draws of one rank take it negative (single deck gave NaN).
  const decksLeft = Math.max(1, Math.round(rules.decks * (1 - rules.penetration / 2) * 100) / 100);
  const edges = {};
  for (let tc = TC_MIN; tc <= TC_MAX; tc++) {
    const game = makeGame(rules, shoeAtTrueCount(tc, decksLeft));
    edges[tc] = Math.round(-houseEdgeCD(rules, game).edge * 1e4) / 1e6; // fraction of the bet, 6 decimals
  }
  out[p.id] = { decksLeft, edges };
  const e = (t) => (edges[t] * 100).toFixed(2);
  console.log(`${p.id.padEnd(16)} D=${decksLeft}  TC0 ${e(0)}%  TC+2 ${e(2)}%  TC+4 ${e(4)}%  (${((Date.now() - t0) / 1000).toFixed(0)}s)`);
}

const body = `// tcedges.js — GENERATED by scripts/build-tcedges.mjs. Do not edit.
// Player edge (fraction of the initial bet, + = player) at each Hi-Lo true count,
// perfect composition-dependent play on the representative shoe for that count,
// at the decks typically left mid-shoe. Keyed by preset id.
export const TC_EDGES = ${JSON.stringify(out)};
`;
writeFileSync(join(root, 'js', 'data', 'tcedges.js'), body);
console.log(`wrote js/data/tcedges.js (${Object.keys(out).length} presets)`);
