// Builds js/data/sources.js from the tables in docs/SOURCES.md, so lessons can
// turn an inline source key (`woo-rules`) into a readable citation link.
// Re-run after editing SOURCES.md:  node scripts/build-sources.mjs
import { readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const md = readFileSync(join(root, 'docs', 'SOURCES.md'), 'utf8');

const out = {};
for (const line of md.split(/\r?\n/)) {
  const m = /^\|\s*`([a-z0-9][a-z0-9-]*)`\s*\|\s*(.+?)\s*\|/.exec(line);
  if (!m) continue;
  const [, key, source] = m;
  const url = (/https?:\/\/[^\s,;)|]+/.exec(source) || [null])[0];
  // the publisher / title: text before the first comma or URL, markdown and asides stripped
  let label = source.split(/,|https?:\/\//)[0]
    .replace(/[*_`"“”]/g, '').replace(/\([^)]*\)?/g, '').replace(/\s+/g, ' ').replace(/[:;.\s]+$/, '').trim();
  label = label.replace(/^BJA(?=\s|$)/, 'Blackjack Apprenticeship');
  if (label.length > 42) label = `${label.slice(0, 40).trim()}…`;
  if (!out[key]) out[key] = { label, url };
}

const body = `// sources.js — GENERATED by scripts/build-sources.mjs from docs/SOURCES.md. Do not edit.
// Inline source keys in lessons (\`woo-rules\`) render as citation links.
export const SOURCES = ${JSON.stringify(out, null, 2)};
`;
writeFileSync(join(root, 'js', 'data', 'sources.js'), body);
console.log(`${Object.keys(out).length} sources -> js/data/sources.js`);
